# Regression Example in Keras

Predicting house prices in Boston, Massachusetts


[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/NSC-BS-CS/CSB410_Labs/blob/main/BookLabs/6-regression_in_keras.ipynb)


#### Load dependencies


In [3]:
import numpy as np
from keras.datasets import boston_housing
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import BatchNormalization

#### Load data


In [4]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [5]:
X_train.shape

(404, 13)

In [6]:
X_valid.shape

(102, 13)

In [7]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [8]:
y_train[0]

np.float64(15.2)

#### Design neural network architecture


In [9]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,185 (4.63 KB)

 Trainable params: 1,089 (4.25 KB)

 Non-trainable params: 96 (384.00 B)

#### Configure Model


In [11]:
model.compile(loss='mean_squared_error', optimizer='adam')

#### Train!


In [12]:
model.fit(X_train, y_train,
          batch_size=8, epochs=32, verbose=1,
          validation_data=(X_valid, y_valid))

Epoch 1/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 588.1234 - val_loss: 587.4984
Epoch 2/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 580.9890 - val_loss: 570.6085
Epoch 3/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 531.9900 - val_loss: 535.0177
Epoch 4/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 493.6886 - val_loss: 491.8568
Epoch 5/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 502.3900 - val_loss: 456.9785
Epoch 6/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 476.1809 - val_loss: 431.6440
Epoch 7/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 504.3584 - val_loss: 413.0425
Epoch 8/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 418.9220 - val_loss: 394.6500
Epoch 9/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 350.9148 - val_loss: 368.9384
Epoch 10/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 342.5927 - val_loss: 281.6284
Epoch 11/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 265.2949 - val_loss: 160.9445
Epoch 12/32
51/51 ━━━━━━━━━━━━

In [13]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [14]:
y_valid[42]

np.float64(14.1)

In [15]:
model.predict(np.reshape(X_valid[42], [1, 13]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step


array([[17.515173]], dtype=float32)